#!/bin/bash

save_dir="/root/make_data"
make_install_dir="/web_server"
libzip_src_dir="/root/hazx/php8/libzip-1.8.0"

# 导出Nginx编译内容
cp -R ${make_install_dir}/nginx ${save_dir}/nginx
mv ${save_dir}/nginx/html ${save_dir}/nginx_df_html
sed -e 's/root\ \ \ html/root\ \/web_server\/nginx_df_html\//' ${save_dir}/nginx/conf/nginx.conf > ${save_dir}/nginx/conf/nginx.conf.tmp
sed -e "1iuser\ root\;" ${save_dir}/nginx/conf/nginx.conf.tmp > ${save_dir}/nginx/conf/nginx.conf
rm -f ${save_dir}/nginx/conf/nginx.conf.tmp

# 导出libzip编译内容
mkdir -p ${save_dir}/libzip/lib
mkdir -p ${save_dir}/libzip/exec
cp ${libzip_src_dir}/build/lib/libzip.* ${save_dir}/libzip/lib/
cp ${libzip_src_dir}/build/src/zip* ${save_dir}/libzip/exec/
cp ${libzip_src_dir}/build/libzip.pc ${save_dir}/libzip/

# 导出PHP8编译内容
cp -R ${make_install_dir}/php ${save_dir}/php

echo "save ok."